### ISSUE TITLE
Remove sleep while shutting down multiple containers

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/tests#635] opened 2018-08-22 19:08 UTC
Now that this issue has been solved https://github.com/kata-containers/agent/pull/263,
it is necessary to remove the workaround of sleeping while shutting down containers.

**Comment by grahamwhaley** [comment] 2018-08-23 08:28
Probably a duplicate of #564

**Closed** 2018-08-23 14:01 UTC
Labels: review
