### ISSUE TITLE
Metrics and VFIO PR tests are consistently failing in Jenkins (connection timed out)

### ISSUE THREAD

**Issue by gkurz** [kata-containers/tests#4204] opened 2021-11-22 10:36 UTC
Metrics and VFIO PR tests are consistently failing in Jenkins CI :

```
Cloning repository https://github.com/kata-containers/tests.git
 > git init /home/jenkins/workspace/workspace/kata-containers-2.0-tests-metrics-ubuntu-20-04-PR # timeout=10
Fetching upstream changes from https://github.com/kata-containers/tests.git
 > git --version # timeout=10
 > git --version # 'git version 2.25.1'
 > git fetch --tags --force --progress -- https://github.com/kata-containers/tests.git +refs/heads/*:refs/remotes/origin/* # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- https://github.com/kata-containers/tests.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: unable to access 'https://github.com/kata-containers/tests.git/': Failed to connect to github.com port 443: Connection timed out
```

This is blocking #4199

**Comment by fidencio** [comment] 2021-11-22 10:44
/cc @GabyCT @chavafg 

Gaby, Chava, it looks like an infra issue, and it may even solve itself during the day.  However, what's the best way to debug those in case we hit them again in the future?

**Comment by fidencio** [comment] 2021-11-22 10:45
Note:  Those two jobs are running on the same baremetal machine, so it smells like the problem is with some configuration in that baremetal machine.

**Comment by chavafg** [comment] 2021-11-22 14:25
I took a look and I thought that a simple reboot would work, but it didn't. Seems that there are network issues on the Equinix infrastructure and I'm talking with them to see if this is something on their side (which seems to be).

**Comment by GabyCT** [comment] 2021-11-22 20:44
Closing this issue as it has been fixed

**Closed by GabyCT** 2021-11-22 20:44 UTC

**Comment by chavafg** [comment] 2021-11-22 22:43
just FYI, we needed to deploy another baremetal instance and move the testing there. We couldn't figured out what was the issue with the old instance. All jobs should now be running on the new instance.
