### ISSUE TITLE
openshift test failing

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/tests#1524] opened 2019-05-01 16:10 UTC
See in a few places recently:

```
Create configuration files
Wrote master config to: /tmp/jenkins/workspace/kata-containers-runtime-fedora-PR/go/src/github.com/kata-containers/tests/integration/openshift/openshift.local.config/master/master-config.yaml
Start Master
In project default on server https://10.0.0.30:8443

You have no services, deployment configs, or build configs.
Run 'oc new-app' to create an application.
Start Node
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                 AGE
service/kubernetes   ClusterIP   172.30.0.1   <none>        443/TCP,53/UDP,53/TCP   0s
Openshift started successfully
1..1
not ok 1 Hello Openshift using Kata Containers
# (in test file hello_world.bats, line 209)
#   `' failed
# fedora28-azure2b2e20   Ready     <none>    11s       v1.10.0+b81c8f8
# W0430 09:56:57.315761  113389 util_unix.go:75] Using "/var/run/crio/crio.sock" as endpoint is deprecated, please consider using full url format "unix:///var/run/crio/crio.sock".
# Image is update to date for docker.io/openshift/hello-openshift@sha256:aaea76ff622d2f8bcb32e538e7b3cd0ef6d291953f3e7c9f556c1ba5baf47e2e
# pod "hello-openshift" created
#     State:          Waiting
# pod "hello-openshift" deleted
# NAME              READY     STATUS        RESTARTS   AGE
# hello-openshift   0/1       Terminating   0          53s
make: *** [Makefile:120: openshift] Error 1
```

Seen on https://github.com/kata-containers/runtime/pull/1610 in Fedora and Fedora vsocks CIs:

- http://jenkins.katacontainers.io/job/kata-containers-runtime-fedora-PR/1994/console
- http://jenkins.katacontainers.io/job/kata-containers-runtime-fedora-vsocks-PR/706/console

**Comment by chavafg** [comment] 2019-05-02 14:49
duplicate of #1522 and PR #1526 should solve this.

**Closed by chavafg** 2019-05-02 14:49 UTC
