### ISSUE TITLE
s390x | test_watch_entries failure

### ISSUE THREAD

**Issue by fidencio** [kata-containers/tests#4183] opened 2021-11-11 10:37 UTC
```
thread 'watcher::tests::test_watch_entries' panicked at 'assertion failed: `(left == right)`
  left: `"original"`,
 right: `"updated"`', src/watcher.rs:732:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test watcher::tests::test_watch_entries ... FAILED
```

cc @Jakob-Naucke @egernst

**Comment by fidencio** [comment] 2021-11-11 10:38
And this happened on http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-s390x-PR/981

**Comment by Jakob-Naucke** [comment] 2021-11-11 10:40
Duplicate of https://github.com/kata-containers/kata-containers/issues/2946, closing

**Closed by Jakob-Naucke** 2021-11-11 10:40 UTC
Labels: bug, duplicate, area/s390x, area/testing, area/agent

**Comment by fidencio** [comment] 2021-11-11 11:56
> Duplicate of [kata-containers/kata-containers#2946](https://github.com/kata-containers/kata-containers/issues/2946), closing

Perfect, thanks!  I was looking for s390x specific reports and missed #2946
