### ISSUE TITLE
jenkins-metrics-ubuntu-20-04 is failing for multiple PRs

### ISSUE THREAD

**Issue by cmaf** [kata-containers/tests#3447] opened 2021-04-27 00:23 UTC
Boot-times in jenkins-metrics-ubuntu-20-04 is failing in multiple PRs with the same error:

```
time="2021-04-26T14:43:07Z" level=debug msg="Processing boot-times"
time="2021-04-26T14:43:07Z" level=debug msg="Process a JSON"
time="2021-04-26T14:43:07Z" level=debug msg="Fullpath /home/jenkins/workspace/workspace/kata-containers-2.0-metrics-ubuntu-20-04-PR/go/src/github.com/kata-containers/tests/metrics/results/boot-times.json"
time="2021-04-26T14:43:07Z" level=debug msg="in json load of [/home/jenkins/workspace/workspace/kata-containers-2.0-metrics-ubuntu-20-04-PR/go/src/github.com/kata-containers/tests/metrics/results/boot-times.json]"
time="2021-04-26T14:43:07Z" level=debug msg=" Run jq '.\"boot-times\".Results | .[] | .\"to-workload\".Result' /home/jenkins/workspace/workspace/kata-containers-2.0-metrics-ubuntu-20-04-PR/go/src/github.com/kata-containers/tests/metrics/results/boot-times.json"
time="2021-04-26T14:43:07Z" level=warning msg="Failed to run [jq .\"boot-times\".Results | .[] | .\"to-workload\".Result /home/jenkins/workspace/workspace/kata-containers-2.0-metrics-ubuntu-20-04-PR/go/src/github.com/kata-containers/tests/metrics/results/boot-times.json][exit status 2]"
time="2021-04-26T14:43:07Z" level=warning msg="[/home/jenkins/workspace/workspace/kata-containers-2.0-metrics-ubuntu-20-04-PR/go/src/github.com/kata-containers/tests/metrics/results/boot-times.json][exit status 2]"

Report Summary:
+-----+--------------------------+---------------------+---------------+--------+-------+--------+--------+------+------+-----+
| P/F |           NAME           |         FLR         |     MEAN      |  CEIL  |  GAP  |  MIN   |  MAX   | RNG  | COV  | ITS |
+-----+--------------------------+---------------------+---------------+--------+-------+--------+--------+------+------+-----+
| *F* | boot-times               | Failed to load JSON | exit status 2 |        |       |        |        |      |      |     |
| P   | memory-footprint         | 95.0%               | 100.2%        | 105.0% | 10.0% | 100.2% | 100.2% | 0.0% | 0.0% |   1 |
| P   | memory-footprint-ksm     | 95.0%               | 100.2%        | 105.0% | 10.0% | 100.2% | 100.2% | 0.0% | 0.0% |   1 |
| P   | blogbench                | 90.0%               | 98.4%         | 110.0% | 20.0% | 98.4%  | 98.4%  | 0.0% | 0.0% |   1 |
| P   | blogbench                | 90.0%               | 95.3%         | 110.0% | 20.0% | 95.3%  | 95.3%  | 0.0% | 0.0% |   1 |
| P   | network-iperf3-bandwidth | 90.0%               | 104.9%        | 110.0% | 20.0% | 104.9% | 104.9% | 0.0% | 0.0% |   1 |
+-----+--------------------------+---------------------+---------------+--------+-------+--------+--------+------+------+-----+
Fails: 1, Passes 5
Failed
checkmetrics FAILED (1)
restoring KSM settings
Failed at 85: sudo -E PATH="$PATH" ".ci/run_metrics_PR_ci.sh"
++ handle_error 73
++ local exit_code=1
++ local line_number=73
++ echo 'Failed at /home/jenkins/workspace/workspace/kata-containers-2.0-metrics-ubuntu-20-04-PR/ci_entry_point.sh +73: .ci/jenkins_job_build.sh "${repo_to_test}"'
Failed at /home/jenkins/workspace/workspace/kata-containers-2.0-metrics-ubuntu-20-04-PR/ci_entry_point.sh +73: .ci/jenkins_job_build.sh "${repo_to_test}"
++ exit 1
```
See https://github.com/kata-containers/tests/pull/3038, https://github.com/kata-containers/kata-containers/pull/1749

**Comment by ariel-adam** [comment] 2021-04-27 14:22
Closing this for now since it's a duplicate of https://github.com/kata-containers/tests/issues/3443

**Closed by ariel-adam** 2021-04-27 14:22 UTC
Labels: area/testing, bug, needs-review
