### ISSUE TITLE
log-parser failed to parse new agent logs

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/tests#228] opened 2018-04-11 02:32 UTC
Got this in kata-containers/agent/pull/211.

> ERROR: kata-log-parser: failed to parse agent log entry {Count:0 TimeDelta:0 Filename:/home/jenkins/jenkins_slave/workspace/kata-containers-agent-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests/kata-proxy.log Line:30839 Time:2018-04-09 15:05:13.57247684 +0000 UTC Pid:119434 Level:info Msg:time="2018-04-09T15:05:13.544663325Z" level=debug msg="new request" name=kata-agent pid=118 req="container_id:\"147ea9e2c6de4ec7cfe76b32be763ea641e55f3ebbee3030e77a6e78a8a817ba\" exec_id:\"147ea9e2c6de4ec7cfe76b32be763ea641e55f3ebbee3030e77a6e78a8a817ba\" storages:<driver:\"scsi\" source:\"0:0\" fstype:\"xfs\" options:\"nouuid\" mount_point:\"/run/kata-containers/shared/containers/147ea9e2c6de4ec7cfe76b32be763ea641e55f3ebbee3030e77a6e78a8a817ba\" > OCI:<Version:\"1.0.0\" Process:<User:<> Args:\"/pause\" Env:\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\" Env:\"TERM=xterm\" Cwd:\"/\" Capabilities:<Bounding:\"CAP_CHOWN\" Bounding:\"CAP_DAC_OVERRIDE\" Bounding:\"CAP_FSETID\" Bounding:\"CAP_FOWNER\" Bounding:\"CAP_MKNOD\" Bounding:\"CAP_NET_RAW\" Bounding:\"CAP_SETGID\" Bounding:\"CAP_SETUID\" Bounding:\"CAP_SETFCAP\" Bounding:\"CAP_SETPCAP\" Bounding:\"CAP_NET_BIND_SERVICE\" Bounding:\"CAP_SYS_CHROOT\" Bounding:\"CAP_KILL\" Bounding:\"CAP_AUDIT_WRITE\" Effective:\"CAP_CHOWN\" Effective:\"CAP_DAC_OVERRIDE\" Effective:\"CAP_FSETID\" Effective:\"CAP_FOWNER\" Effective:\"CAP_MKNOD\" Effective:\"CAP_NET_RAW\" Effective:\"CAP_SETGID\" Effective:\"CAP_SETUID\" Effective:\"CAP_SETFCAP\" Effective:\"CAP_SETPCAP\" Effective:\"CAP_NET_BIND_SERVICE\" Effective:\"CAP_SYS_CHROOT\" Effective:\"CAP_KILL\" Effective:\"CAP_AUDIT_WRITE\" Inheritable:\"CAP_CHOWN\" Inheritable:\"CAP_DAC_OVERRIDE\" Inheritable:\"CAP_FSETID\" Inheritable:\"CAP_FOWNER\" Inheritable:\"CAP_MKNOD\" Inheritable:\"CAP_NET_RAW\" Inheritable:\"CAP_SETGID\" Inheritable:\"CAP_SETUID\" Inheritable:\"CAP_SETFCAP\" Inheritable:\"CAP_SETPCAP\" Inheritable:\"CAP_NET_BIND_SERVICE\" Inheritable:\"CAP_SYS_CHROOT\" Inheritable:\"CAP_KILL\" Inheritable:\"CAP_AUDIT_WRITE\" Permitted:\"CAP_CHOWN\" Permitted:\"CAP_DAC_OVERRIDE\" Permitted:\"CAP_FSETID\" Permitted:\"CAP_FOWNER\" Permitted:\"CAP_MKNOD\" Permitted:\"CAP_NET_RAW\" Permitted:\"CAP_SETGID\" Permitted:\"CAP_SETUID\" Permitted:\"CAP_SETFCAP\" Permitted:\"CAP_SETPCAP\" Permitted:\"CAP_NET_BIND_SERVICE\" Permitted:\"CAP_SYS_CHROOT\" Permitted:\"CAP_KILL\" Permitted:\"CAP_AUDIT_WRITE\" Ambient:\"CAP_CHOWN\" Ambient:\"CAP_DAC_OVERRIDE\" Ambient:\"CAP_FSETID\" Ambient:\"CAP_FOWNER\" Ambient:\"CAP_MKNOD\" Ambient:\"CAP_NET_RAW\" Ambient:\"CAP_SETGID\" Ambient:\"CAP_SETUID\" Ambient:\"CAP_SETFCAP\" Ambient:\"CAP_SETPCAP\" Ambient:\"CAP_NET_BIND_SERVICE\" Ambient:\"CAP_SYS_CHROOT\" Ambient:\"CAP_KILL\" Ambient:\"CAP_AUDIT_WRITE\" > Rlimits:<Type:\"RLIMIT_NOFILE\" Hard:1024 Soft:1024 > OOMScoreAdj:-998 > Root:<Path:\"/run/kata-containers/shared/containers/147ea9e2c6de4ec7cfe76b32be763ea641e55f3ebbee3030e77a6e78a8a817ba/rootfs\" Readonly:true > Hostname:\"crictl_host\" Mounts:<destination:\"/proc\" source:\"proc\" type:\"proc\" > Mounts:<destination:\"/dev\" source:\"tmpfs\" type:\"tmpfs\" options:\"nosuid\" options:\"strictatime\" options:\"mode=755\" options:\"size=65536k\" > Mounts:<destination:\"/dev/pts\" source:\"devpts\" type:\"devpts\" options:\"nosuid\" options:\"noexec\" options:\"newinstance\" options:\"ptmxmode=0666\" options:\"mode=0620\" options:\"gid=5\" > Mounts:<destination:\"/dev/shm\" source:\"shm\" type:\"tmpfs\" options:\"noexec\" options:\"nosuid\" options:\"nodev\" options:\"mode=1777\" options:\"size=65536k\" > Mounts:<destination:\"/dev/mqueue\" source:\"mqueue\" type:\"mqueue\" options:\"nosuid\" options:\"noexec\" options:\"nodev\" > Mounts:<destination:\"/sys\" source:\"sysfs\" type:\"sysfs\" options:\"nosuid\" options:\"noexec\" options:\"nodev\" options:\"ro\" > Mounts:<destination:\"/etc/resolv.conf\" source:\"/run/kata-containers/shared/containers/147ea9e2c6de4ec7cfe76b32be763ea641e55f3ebbee3030e77a6e78a8a817ba-9f55d8edab352c42-resolv.conf\" type:\"bind\" options:\"ro\" options:\"bind\" > Mounts:<destination:\"/etc/hostname\" source:\"/run/kata-containers/shared/containers/147ea9e2c6de4ec7cfe76b32be763ea641e55f3ebbee3030e77a6e78a8a817ba-e6ac26e745adf824-hostname\" type:\"bind\" options:\"ro\" options:\"bind\" > Annotations:<key:\"group\" value:\"test\" > Annotations:<key:\"io.kuberne[    1.193303] sd 0:0:0:0: [sda] Attached SCSI disk
 Source:agent Name:kata-proxy Data:map[]}: failed to parse file "/home/jenkins/jenkins_slave/workspace/kata-containers-agent-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests/kata-proxy.log", line 1: logfmt syntax error at pos 4148 on line 1: unterminated quoted value (keyvals: [{key:time value:2018-04-09T15:05:13.544663325Z} {key:level value:debug} {key:msg value:new request} {key:name value:kata-agent} {key:pid value:118}])

**Comment by sboeuf** [comment] 2018-04-11 09:18
@devimc is that something you're actively tracking ? I am asking because we must fix those CI issues rather sooner than later since they are still preventing some PR from being merged.
/cc @grahamwhaley @jcvenegas @amshinde @chavafg

**Comment by bergwolf** [comment] 2018-04-11 09:29
I'm wondering why are we testing the log-parser in runtime CI tests? As I understand it, such tests can just be done in its own CI. There is no way a runtime change should break the log-parser, unless the log-parser is broken itself.

**Comment by grahamwhaley** [comment] 2018-04-11 09:31
I don't think that is a log parser unit test failure @bergwolf - I think that is the log parser doing its job and saying that the agent log entry was not formatted correctly - and hence failed the CI ?

**Comment by bergwolf** [comment] 2018-04-11 09:39
@grahamwhaley that line of log is formated via 
```
	agentLog.WithFields(logrus.Fields{
		"request": info.FullMethod,
		"req":     message.String()}).Debug("new request")
```
Is there any chance it can be malformed?

**Comment by bergwolf** [comment] 2018-04-13 03:11
@kata-containers/tests what's the plan to solve the issue? FWIW, it seems to be a flaw in the log-parser because it expects the guest console outputs to be well-formated, which is not always true because the guest kernel can also print to the console and interfere with the kata agent logs.

**Comment by sboeuf** [comment] 2018-04-13 08:17
@bergwolf my best bet here is that we might end up disabling `kata-log-parser` while it's getting fixed. @jodh-intel will be back from vacation on Monday, let's wait for his input on this, and let's take a decision afterwards.

**Comment by bergwolf** [comment] 2018-04-17 14:54
@jodh-intel what's your opinion on this one? It's blocking kata-containers/agent/pull/211 right now.

**Comment by jodh-intel** [comment] 2018-04-17 15:30
@bergwolf - the CI doesn't call the log parser to test the log parser, it calls the tool:

- to look for badly formed log messages from any kata component.
- to ensure (as far as possible) that all the kata log messages are "well-formed" and machine parseable.

As for the immediate problem, yes the problem is that the guest kernel is "corrupting" the terminal output from the viewpoint of the log parser.

I guess we have a few options:

- Disable kernel console output.

  This is not ideal given that we need such output for debugging purposes. Although we could redirect console output to the journal, I don't know if that would work if the agent is acting as the init daemon?

- Make the agent log somewhere else.

  This isn't ideal either given that the agent can run in two different modes (systemd service and init daemon).

- Change the log parser to ignore "corrupt" agent messages logged by the proxy.

  This isn't really ideal either as it lowers the utility of the log parser tool but would allow us to handle the occasional async message from the kernel and avoid it killing the CI. I guess we could always make that behaviour the default but add a `--strict` option to the log parser to make it fail in such circumstances (in other words with that option, it would be have as it does now).

Any other ideas folk?

**Comment by sboeuf** [comment] 2018-04-17 18:34
@jodh-intel do you think we can make the parser a bit smarter and actually handle such cases ? Or is that really complex to handle ?

**Comment by jodh-intel** [comment] 2018-04-18 06:14
As stated above, I think the best we can do is ignore "corrupt" lines. I'll raise a PR for this later and make it the default to unblock the CI. It's not a great solution though since that change could hide issues with the agent logs...

**Closed** 2018-04-20 18:09 UTC
Labels: review
