### ISSUE TITLE
Random failures at CI for s390x

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/tests#4285] opened 2021-12-13 20:15 UTC
I have seen random failures for the s390x CI in different PRs see http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-s390x-PR/533/console, http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-s390x-PR/512/console
```
11:22:48 --- PASS: TestWaitLocalProcess (0.15s)
11:22:48 === RUN   TestWaitLocalProcessInvalidSignal
11:22:48 --- PASS: TestWaitLocalProcessInvalidSignal (0.00s)
11:22:48 === RUN   TestWaitLocalProcessInvalidPid
11:22:48 --- PASS: TestWaitLocalProcessInvalidPid (0.00s)
11:22:48 === RUN   TestMkdirAllWithInheritedOwnerSuccessful
11:22:48 --- PASS: TestMkdirAllWithInheritedOwnerSuccessful (0.00s)
11:22:48 === RUN   TestChownToParent
11:22:48 --- PASS: TestChownToParent (0.00s)
11:22:48 === RUN   TestGetAllParentPaths
11:22:48 --- PASS: TestGetAllParentPaths (0.00s)
11:22:48 PASS
11:22:48 ok  	github.com/kata-containers/kata-containers/src/runtime/virtcontainers/utils	0.235s
11:22:48 FAIL
11:22:48 make[1]: *** [Makefile:598: go-test] Error 1
11:22:48 make[1]: Leaving directory '/home/jenkins/workspace/kata-containers-2.0-tests-ubuntu-s390x-PR/go/src/github.com/kata-containers/kata-containers/src/runtime'
11:22:48 make: *** [Makefile:31: test-runtime] Error 2
```

**Comment by GabyCT** [comment] 2021-12-13 20:26
```
11:22:48 === RUN   TestMonitor
11:22:48     sandbox_test.go:994: 
11:22:48         	Error Trace:	sandbox_test.go:994
11:22:48         	Error:      	Expected nil, but got: &fs.PathError{Op:"open", Path:"/tmp/vc/mockfs/sbs/7f49d00d-1995-4156-8c79-5f5ab24ce138", Err:0x2}
11:22:48         	Test:       	TestMonitor
11:22:48         	Messages:   	VirtContainers should not allow empty sandboxes
11:22:48 --- FAIL: TestMonitor (0.04s)
11:22:48 panic: runtime error: invalid memory address or nil pointer dereference [recovered]
11:22:48 	panic: runtime error: invalid memory address or nil pointer dereference
11:22:48 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9dc39e]
11:22:48 
11:22:48 goroutine 700 [running]:
11:22:48 testing.tRunner.func1.2({0xb251a0, 0x148e4a0})
11:22:48 	/usr/local/go/src/testing/testing.go:1209 +0x2e2
11:22:48 testing.tRunner.func1(0xc000b6bba0)
11:22:48 	/usr/local/go/src/testing/testing.go:1212 +0x236
11:22:48 panic({0xb251a0, 0x148e4a0})
11:22:48 	/usr/local/go/src/runtime/panic.go:1038 +0x228
11:22:48 github.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*Sandbox).Monitor(0x0, {0xdd4710, 0xc0001b0000})
11:22:48 	/home/jenkins/workspace/kata-containers-2.0-tests-ubuntu-s390x-PR/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/sandbox.go:334 +0x1e
11:22:48 github.com/kata-containers/kata-containers/src/runtime/virtcontainers.TestMonitor(0xc000b6bba0)
11:22:48 	/home/jenkins/workspace/kata-containers-2.0-tests-ubuntu-s390x-PR/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/sandbox_test.go:997 +0x1a4
11:22:48 testing.tRunner(0xc000b6bba0, 0xca0380)
11:22:48 	/usr/local/go/src/testing/testing.go:1259 +0xf8
11:22:48 created by testing.(*T).Run
11:22:48 	/usr/local/go/src/testing/testing.go:1306 +0x3da
11:22:48 FAIL	github.com/kata-containers/kata-containers/src/runtime/virtcontainers	2.295s
```

**Comment by Jakob-Naucke** [comment] 2021-12-14 10:39
@GabyCT duplicate of https://github.com/kata-containers/kata-containers/issues/2987, but thanks for the reminder

**Closed by Jakob-Naucke** 2021-12-14 10:39 UTC
Labels: bug, duplicate, needs-review, area/ci, area/s390x
